# version: "3.8" docker compose v2 (=the cli plugin) will always use the latest version
services:
  web:
    build:
      context: .
      # Correct the path to your Dockerfile
      dockerfile: Dockerfile
    ports:
      - 3000:8080
    # Important to bind/mount your codebase dir to /app dir for live reload
    volumes:
      - ./:/app
